/-
  The trichotomy: conservativity, non-uniqueness, or non-uniformity.

  Over a consistent symmetric base theory, any schema satisfies at least one
  of

    (C)  it is conservative;
    (U)  it does not have exactly one consistent extension;
    (P)  it is not proposition-uniform.

  You may have new conclusions, or a determinate answer, or a uniform rule.
  Not all three.

  Three things about the development.

  * Step 1 of the paper's proof — that the unique extension is invariant under
    the automorphism group — is not reproved here.  It is
    `LogAut.isExtension_pre` from `Rigidity.lean`, applied to an atom
    automorphism instead of to the shift.  The two steps really are one lemma,
    which is why that file states it for an arbitrary logical automorphism.

  * The compactness step the paper flags at the end of Step 2 does not appear.
    The paper collects the whole orbit `{gφ}` of the offending sentence, argues
    that `T ∪ {gφ}` is unsatisfiable, and then needs compactness to turn
    unsatisfiability into a derivation of `⊥`.  With a semantic consequence
    operator there is nothing to convert: a theory with no model is
    inconsistent by definition.  The argument below does not even form the
    orbit — it takes the single automorphism carrying the counter-model to the
    model already in hand.  The paper's remark that this is "the only place
    where the infinite index set does any work" can be dropped: it does none.

  * `Aut(L)` is realised concretely, and this is what forced the signed-atom
    syntax in `Uniformity.lean`.  With unsigned atoms an element of `Aut(L)`
    is a bijection of formulas only up to logical equivalence — `¬¬a` and `a`
    are distinct formulas — so it acts on the Lindenbaum algebra and not on
    formulas, and the preimage of a schema is not the schema.  With signed
    atoms `autForm` is a genuine involution-generated bijection and the
    transport goes through unchanged.
-/

import Development.Rigidity

set_option autoImplicit false

namespace TranscendenceTower.Uniformity

variable {A C : Type}

/-! ## Two facts about `xor` -/

theorem xor_cancel (x y : Bool) : xor (xor x y) y = x := by
  cases x <;> cases y <;> rfl

theorem xor_cancel_left (x y : Bool) : xor x (xor x y) = y := by
  cases x <;> cases y <;> rfl

theorem xor_assoc' (x y z : Bool) : xor (xor x y) z = xor x (xor y z) := by
  cases x <;> cases y <;> cases z <;> rfl

/-! ## Atom automorphisms

An element of `Aut(L)` is given by a permutation `π` of the atoms together
with a sign pattern `ε`, which may be an arbitrary function — see the paper's
remark on why the group generated by permutations and single-atom negations is
too small to be transitive.  Context indices are fixed; the map acts inside
the scope of `ist`. -/

/-- The action of `(π, ε)` on formulas. -/
def autForm (π : A ≃ A) (ε : A → Bool) : CForm A C → CForm A C
  | .lit a b => .lit (π a) (xor b (ε a))
  | .fls => .fls
  | .impl p q => .impl (autForm π ε p) (autForm π ε q)
  | .ist c p => .ist c (autForm π ε p)

/-- The sign pattern of the inverse. -/
def invEps (π : A ≃ A) (ε : A → Bool) : A → Bool := fun a => ε (π.symm a)

theorem autForm_symm_autForm (π : A ≃ A) (ε : A → Bool) (p : CForm A C) :
    autForm π.symm (invEps π ε) (autForm π ε p) = p := by
  induction p with
  | lit a b => simp [autForm, invEps, Equiv.symm_apply_apply, xor_cancel]
  | fls => rfl
  | impl p q ihp ihq => simp [autForm, ihp, ihq]
  | ist c p ih => simp [autForm, ih]

theorem autForm_autForm_symm (π : A ≃ A) (ε : A → Bool) (p : CForm A C) :
    autForm π ε (autForm π.symm (invEps π ε) p) = p := by
  induction p with
  | lit a b => simp [autForm, invEps, Equiv.apply_symm_apply, xor_cancel]
  | fls => rfl
  | impl p q ihp ihq => simp [autForm, ihp, ihq]
  | ist c p ih => simp [autForm, ih]

/-- An atom automorphism is a genuine bijection of formulas.  This is what the
signed-atom syntax buys. -/
def autFormEquiv (π : A ≃ A) (ε : A → Bool) : CForm A C ≃ CForm A C where
  toFun := autForm π ε
  invFun := autForm π.symm (invEps π ε)
  left_inv := autForm_symm_autForm π ε
  right_inv := autForm_autForm_symm π ε

/-- The atom automorphisms preserve the base language. -/
theorem autForm_isBase (π : A ≃ A) (ε : A → Bool) :
    ∀ p : CForm A C, IsBase p → IsBase (autForm π ε p) := by
  intro p
  induction p with
  | lit a b => intro _; trivial
  | fls => intro _; trivial
  | impl p q ihp ihq => intro hb; exact ⟨ihp hb.1, ihq hb.2⟩
  | ist c p _ => intro hb; exact hb.elim

theorem autForm_neg (π : A ≃ A) (ε : A → Bool) (p : CForm A C) :
    autForm π ε (neg p) = neg (autForm π ε p) := by
  cases p with
  | lit a b => cases b <;> cases h : ε a <;> simp [autForm, h]
  | fls => rfl
  | impl p q => rfl
  | ist c p => rfl

/-- The valuation an atom automorphism pulls back. -/
def autVal (π : A ≃ A) (ε : A → Bool) (v : CVal A C) : CVal A C where
  atom a := xor (ε a) (v.atom (π a))
  ist c p := v.ist c (autForm π ε p)

theorem eval_autForm (π : A ≃ A) (ε : A → Bool) (v : CVal A C) (p : CForm A C) :
    eval v (autForm π ε p) = eval (autVal π ε v) p := by
  induction p with
  | lit a b => simp [autForm, eval, autVal, xor_assoc']
  | fls => rfl
  | impl p q ihp ihq => simp [eval, autForm, ihp, ihq]
  | ist c p _ => rfl

theorem autVal_symm_autVal (π : A ≃ A) (ε : A → Bool) (v : CVal A C) :
    autVal π.symm (invEps π ε) (autVal π ε v) = v := by
  refine cval_ext ?_ ?_
  · funext a
    simp [autVal, invEps, Equiv.apply_symm_apply, xor_cancel_left]
  · funext c p
    show v.ist c (autForm π ε (autForm π.symm (invEps π ε) p)) = v.ist c p
    rw [autForm_autForm_symm]

theorem autVal_autVal_symm (π : A ≃ A) (ε : A → Bool) (v : CVal A C) :
    autVal π ε (autVal π.symm (invEps π ε) v) = v := by
  refine cval_ext ?_ ?_
  · funext a
    simp [autVal, invEps, Equiv.symm_apply_apply]
  · funext c p
    show v.ist c (autForm π.symm (invEps π ε) (autForm π ε p)) = v.ist c p
    rw [autForm_symm_autForm]

/-- and a bijection of valuations. -/
def autValEquiv (π : A ≃ A) (ε : A → Bool) : CVal A C ≃ CVal A C where
  toFun := autVal π ε
  invFun := autVal π.symm (invEps π ε)
  left_inv := autVal_symm_autVal π ε
  right_inv := autVal_autVal_symm π ε

/-- An atom automorphism, packaged for the transport lemma. -/
def autAut (π : A ≃ A) (ε : A → Bool) : LogAut A C where
  form := autFormEquiv π ε
  val := autValEquiv π ε
  eval_form := eval_autForm π ε
  form_neg := autForm_neg π ε

/-- The group, as a set of logical automorphisms. -/
def AutL (A C : Type) : Set (LogAut A C) :=
  {g | ∃ (π : A ≃ A) (ε : A → Bool), g = autAut π ε}

/-! ## Proposition-uniformity gives invariance of the schema

The paper's Step 1 asserts that `g(S) = S` follows from proposition-uniformity
because `g` is invertible.  That is exactly right, and the proof is: an atom
automorphism *is* a substitution, so uniformity gives one inclusion, and its
inverse is another substitution, which gives the other. -/

/-- An atom automorphism, read as a substitution. -/
def autSubst (π : A ≃ A) (ε : A → Bool) : A → CForm A C :=
  fun a => CForm.lit (π a) (ε a)

theorem autForm_eq_subst (π : A ≃ A) (ε : A → Bool) (p : CForm A C) :
    autForm π ε p = subst (autSubst π ε) p := by
  induction p with
  | lit a b => cases b <;> simp [autForm, subst, autSubst, neg]
  | fls => rfl
  | impl p q ihp ihq => simp [autForm, subst, ihp, ihq]
  | ist c p ih => simp [autForm, subst, ih]

/-- The action of a substitution on a rule. -/
def substRule (s : A → CForm A C) (r : Rule A C) : Rule A C :=
  ⟨subst s r.prereq, subst s r.justif, subst s r.conseq⟩

/-- A schema is proposition-uniform when its rules are closed under every
substitution. -/
def PropUniformRules (S : Set (Rule A C)) : Prop :=
  ∀ (s : A → CForm A C), ∀ r ∈ S, substRule s r ∈ S

theorem mapRule_autAut (π : A ≃ A) (ε : A → Bool) (r : Rule A C) :
    (autAut π ε).mapRule r = substRule (autSubst π ε) r := by
  simp [LogAut.mapRule, substRule, autAut, autFormEquiv, autForm_eq_subst]

/-- **Proposition-uniformity implies invariance of the schema under
`Aut(L)`.** -/
theorem preRules_autAut {S : Set (Rule A C)} (hU : PropUniformRules S)
    (π : A ≃ A) (ε : A → Bool) : (autAut π ε).preRules S = S := by
  ext r
  constructor
  · intro hr
    have hmem : (autAut π ε).mapRule r ∈ S := hr
    have := hU (autSubst π.symm (invEps π ε)) _ hmem
    rw [← mapRule_autAut] at this
    have hcomp : (autAut π.symm (invEps π ε)).mapRule ((autAut π ε).mapRule r) = r := by
      obtain ⟨pre, just, con⟩ := r
      simp [LogAut.mapRule, autAut, autFormEquiv, autForm_symm_autForm]
    rwa [hcomp] at this
  · intro hr
    show (autAut π ε).mapRule r ∈ S
    rw [mapRule_autAut]
    exact hU _ r hr

/-! ## Symmetry -/

/-- `T` is symmetric under `G` when the group moves any model of `T` to any
other.  Only the atoms matter, since `T` and the sentences at issue are in the
base language. -/
def SymmetricUnder (G : Set (LogAut A C)) (T : Set (CForm A C)) : Prop :=
  ∀ M N : CVal A C, Models T M → Models T N →
    ∃ g ∈ G, (g.val.symm M).atom = N.atom

/-- **The tautological theory is symmetric.**  Flip the atoms where the two
valuations disagree; no permutation is needed.  Note that the flip has
arbitrary support, which is why `Aut(L)` must not be defined as the group
*generated by* single-atom negations. -/
theorem symmetricUnder_taut : SymmetricUnder (AutL A C) (∅ : Set (CForm A C)) := by
  intro M N _ _
  refine ⟨autAut (Equiv.refl A) (fun a => xor (M.atom a) (N.atom a)),
    ⟨Equiv.refl A, _, rfl⟩, ?_⟩
  funext a
  show xor (invEps (Equiv.refl A) (fun a => xor (M.atom a) (N.atom a)) a)
      (M.atom ((Equiv.refl A).symm a)) = N.atom a
  simp only [invEps, Equiv.refl_symm, Equiv.refl_apply]
  cases M.atom a <;> cases N.atom a <;> rfl

/-- Every atom automorphism preserves the tautological consequences. -/
theorem autAut_pre_Cn_empty (π : A ≃ A) (ε : A → Bool) :
    (autAut π ε : LogAut A C).pre (Cn (∅ : Set (CForm A C)))
      = Cn (∅ : Set (CForm A C)) := by
  have h : (autAut π ε : LogAut A C).pre (∅ : Set (CForm A C)) = ∅ :=
    Set.preimage_empty
  rw [← LogAut.Cn_pre, h]

/-! ## The trichotomy -/

variable {T : Set (CForm A C)} {S : Set (Rule A C)} {E : Set (CForm A C)}

theorem Cn_subset_extension (hE : IsExtension T S E) : Cn T ⊆ E := by
  rw [hE]
  intro p hp
  exact Set.mem_iUnion.mpr ⟨0, hp⟩

/-- **The trichotomy, in contrapositive form.**  If the schema is invariant
under a group that is transitive on the models of `T`, and the extension is
unique and consistent, then nothing new arrives at the base language. -/
theorem trichotomy_core {G : Set (LogAut A C)}
    (hGT : ∀ g ∈ G, g.pre (Cn T) = Cn T)
    (hGS : ∀ g ∈ G, g.preRules S = S)
    (hGB : ∀ g ∈ G, ∀ p : CForm A C, IsBase p → IsBase (g.form p))
    (hsym : SymmetricUnder G T)
    (hE : IsExtension T S E) (hcon : Consistent E)
    (huniq : ∀ E', IsExtension T S E' → Consistent E' → E' = E) :
    ∀ φ : CForm A C, IsBase φ → φ ∈ E → φ ∈ Cn T := by
  intro φ hφ hmemE
  by_contra hnot
  simp only [Cn, Set.mem_setOf_eq] at hnot
  push Not at hnot
  obtain ⟨M, hMT, hMφ⟩ := hnot
  obtain ⟨v, hv⟩ := id hcon
  -- The model of `E` is in particular a model of `T`.
  have hvT : Models T v := fun q hq => hv q (Cn_subset_extension hE (subset_Cn T hq))
  -- Move the counter-model onto it.
  obtain ⟨g, hgG, hatom⟩ := hsym M v hMT hvT
  -- Step 1: the extension is invariant.
  have hinv : g.pre E = E :=
    huniq _ (LogAut.isExtension_pre g (hGT g hgG) (hGS g hgG) hE)
      (LogAut.consistent_pre g hcon)
  have hgφ : g.form φ ∈ E := by
    have : φ ∈ g.pre E := by rw [hinv]; exact hmemE
    exact this
  -- Step 2: but `g φ` is false in that model.
  have hfalse : eval (g.val.symm M) (g.form φ) = false := by
    rw [g.eval_form, g.val.apply_symm_apply]
    simpa using hMφ
  have hbase : IsBase (g.form φ) := hGB g hgG φ hφ
  have : eval v (g.form φ) = false := by
    rw [eval_base_congr hatom.symm _ hbase]
    exact hfalse
  rw [hv _ hgφ] at this
  exact Bool.noConfusion this

/-- **The trichotomy.**  At least one of the three disjuncts holds:
conservativity, failure of uniqueness, or failure of uniformity. -/
theorem trichotomy {G : Set (LogAut A C)}
    (hGT : ∀ g ∈ G, g.pre (Cn T) = Cn T)
    (hGB : ∀ g ∈ G, ∀ p : CForm A C, IsBase p → IsBase (g.form p))
    (hsym : SymmetricUnder G T)
    (hE : IsExtension T S E) (hcon : Consistent E) :
    (∀ φ : CForm A C, IsBase φ → φ ∈ E → φ ∈ Cn T)
    ∨ (¬ ∀ E', IsExtension T S E' → Consistent E' → E' = E)
    ∨ (¬ ∀ g ∈ G, g.preRules S = S) := by
  by_cases hP : ∀ g ∈ G, g.preRules S = S
  · by_cases hU : ∀ E', IsExtension T S E' → Consistent E' → E' = E
    · exact Or.inl (trichotomy_core hGT hP hGB hsym hE hcon hU)
    · exact Or.inr (Or.inl hU)
  · exact Or.inr (Or.inr hP)

/-- The trichotomy over the tautological base theory, which is the case
McCarthy's question is about: the base is assumed to contribute nothing, so any
novelty would have to come from the tower. -/
theorem trichotomy_taut {S : Set (Rule A C)} {E : Set (CForm A C)}
    (hE : IsExtension (∅ : Set (CForm A C)) S E) (hcon : Consistent E) :
    (∀ φ : CForm A C, IsBase φ → φ ∈ E → φ ∈ Cn (∅ : Set (CForm A C)))
    ∨ (¬ ∀ E', IsExtension (∅ : Set (CForm A C)) S E' → Consistent E' → E' = E)
    ∨ (¬ ∀ g ∈ AutL A C, g.preRules S = S) := by
  refine trichotomy ?_ ?_ symmetricUnder_taut hE hcon
  · rintro g ⟨π, ε, rfl⟩
    exact autAut_pre_Cn_empty π ε
  · rintro g ⟨π, ε, rfl⟩ p hp
    exact autForm_isBase π ε p hp

/-! ## Corner (C) is occupied

The copy schema is proposition-uniform, so `Aut(L)` preserves it, and it is
monotone, so its consistent extension is unique.  The trichotomy therefore
places it in (C), and that is proved rather than assumed: nothing new arrives
at the base language. -/

section Copy

theorem copyRules_propUniform : PropUniformRules (copyRules A C) := by
  rintro s r ⟨c, p, rfl⟩
  exact ⟨c, subst s p, rfl⟩

/-- The copy schema is invariant under the whole automorphism group. -/
theorem copyRules_autInvariant :
    ∀ g ∈ AutL A C, g.preRules (copyRules A C) = copyRules A C := by
  rintro g ⟨π, ε, rfl⟩
  exact preRules_autAut copyRules_propUniform π ε

/-- **The copy schema is conservative over the tautological theory**, by the
trichotomy rather than by direct computation.  This is the corner the paper
assigns it. -/
theorem copy_conservative (atomv : A → Bool) :
    ∀ φ : CForm A C, IsBase φ →
      φ ∈ (⋃ i, stage (∅ : Set (CForm A C)) (copyRules A C) ∅ i) →
      φ ∈ Cn (∅ : Set (CForm A C)) := by
  have hc : Consistent (⋃ i, stage (∅ : Set (CForm A C)) (copyRules A C) ∅ i) := by
    refine ⟨canonVal atomv, ?_⟩
    intro q hq
    obtain ⟨i, hi⟩ := Set.mem_iUnion.mp hq
    exact canonVal_models_stage atomv i q hi
  have hE := isExtension_monotone (T := (∅ : Set (CForm A C))) copyRules_monotone hc
  refine trichotomy_core (G := AutL A C) ?_ copyRules_autInvariant ?_
    symmetricUnder_taut hE hc
    (fun E' hE' hcE' => monotone_unique copyRules_monotone hE hc hE' hcE')
  · rintro g ⟨π, ε, rfl⟩
    exact autAut_pre_Cn_empty π ε
  · rintro g ⟨π, ε, rfl⟩ p hp
    exact autForm_isBase π ε p hp

end Copy

section Verification

#print axioms autFormEquiv
#print axioms preRules_autAut
#print axioms symmetricUnder_taut
#print axioms trichotomy_core
#print axioms trichotomy
#print axioms trichotomy_taut
#print axioms copy_conservative

end Verification

end TranscendenceTower.Uniformity
